import React from "react";
import './pages.css'

function Pc() {
    return <div>
        <a href="https://uk.pcpartpicker.com/list/2DvWqm">PCPartPicker Part List</a>
<table class="pcpp-part-list">
  <thead>
    <tr>
      <th>Type</th>
      <th>Item</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="pcpp-part-list-type">CPU</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/qtvqqs/amd-ryzen-7-5800x-38-ghz-8-core-processor-100-100000063wof">AMD Ryzen 7 5800X 3.8 GHz 8-Core Processor</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/qtvqqs/amd-ryzen-7-5800x-38-ghz-8-core-processor-100-100000063wof">£203.57 @ Amazon UK</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Memory</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/p6RFf7/corsair-memory-cmk16gx4m2b3200c16">Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4-3200 CL16 Memory</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/p6RFf7/corsair-memory-cmk16gx4m2b3200c16">£46.39 @ Scan.co.uk</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Storage</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/mwrYcf/seagate-barracuda-computer-2-tb-35-7200rpm-internal-hard-drive-st2000dm008">Seagate Barracuda Compute 2 TB 3.5" 7200 RPM Internal Hard Drive</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/mwrYcf/seagate-barracuda-computer-2-tb-35-7200rpm-internal-hard-drive-st2000dm008">£46.59 @ BT Shop</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Video Card</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/8HBG3C/asrock-radeon-rx-6700-xt-12-gb-challenger-d-video-card-rx6700xt-cld-12g">ASRock Radeon RX6700XT CLD 12G Radeon RX 6700 XT 12 GB Video Card</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/8HBG3C/asrock-radeon-rx-6700-xt-12-gb-challenger-d-video-card-rx6700xt-cld-12g">£429.89 @ Overclockers.co.uk</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Case</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/vcKKHx/nzxt-h7-elite-atx-mid-tower-case-cm-h71ew-01">NZXT H7 Elite ATX Mid Tower Case</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/vcKKHx/nzxt-h7-elite-atx-mid-tower-case-cm-h71ew-01">£179.99 @ Amazon UK</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Power Supply</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/RhH8TW/gigabyte-750-w-80-gold-certified-fully-modular-atx-power-supply-gp-p750gm">Gigabyte P750GM 750 W 80+ Gold Certified Fully Modular ATX Power Supply</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/RhH8TW/gigabyte-750-w-80-gold-certified-fully-modular-atx-power-supply-gp-p750gm">£77.44 @ Box Limited</a>
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Operating System</td>
      <td class="pcpp-part-list-item"><a href="https://uk.pcpartpicker.com/product/dKkWGX/microsoft-windows-11-home-oem-dvd-64-bit-kw9-00633">Microsoft Windows 11 Home OEM - DVD 64-bit</a></td>
      <td class="pcpp-part-list-price">
        <a href="https://uk.pcpartpicker.com/product/dKkWGX/microsoft-windows-11-home-oem-dvd-64-bit-kw9-00633">£114.99 @ AWD-IT</a>
      </td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Prices include shipping, taxes, rebates, and discounts</td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-total">Total</td>
      <td class="pcpp-part-list-total-price">£1098.86</td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Generated by <a href="https://pcpartpicker.com">PCPartPicker</a> 2023-01-31 13:39 GMT+0000</td>
      <td></td>
    </tr>
  </tbody>
</table>
    </div>
}

export default Pc;